warp-ds/elements

.github/workflows/release.yml, package.json
Allow the latest version of the package to be imported from eik server without the need to update the version number every time a new bundle version is published.
`https://assets.finn.no/pkg/@warp-ds/vue/v1/index.js` 
instead of
`https://assets.finn.no/pkg/@warp-ds/vue/v1.0.0-alpha.9/index.js`
More info on aliases in eik can be found [here](https://eik.dev/docs/client_aliases/).
When `1.0.0` version is published to NPM (`alpha` is merged to `main`), the `eik pkg-alias` script should only be run on pushes to `main`, which will be handled in [this task](https://trello.com/c/IfLXuWlg).
=> feat(workflows): add eik aliasing script to release.yml

package.json, packages/breadcrumbs/index.js, packages/breadcrumbs/test.js, pnpm-lock.yaml
- update the breadcrumbs component to use [component-classes](https://github.com/warp-ds/component-classes/blob/alpha/index.js#L310-L315)
- color tokens work
- handle nested arrays of children like in React and Vue
- allow for overriding the default `aria-label` value
- render `string`-typed children as styled `span` elements with `aria-current="page"` on last child
=> fix: add Warp component-classes to the breadcrumbs component

packages/affix/index.js, packages/alert/index.js, packages/attention/index.js, packages/box/index.js, packages/breadcrumbs/index.js, packages/broadcast/component.js, packages/button/index.js, packages/card/index.js, packages/expandable/index.js, packages/select/index.js, packages/textfield/index.js, packages/toast/toast-container.js, packages/toast/toast.js, packages/utils/expand-transition.js, packages/utils/unstyled-heading.js
The placeholder worked regardless the wrapping comments but we remove it to avoid confusion.
=> chore: remove comments wrapping @unocss-placeholder in components styles

packages/card/index.js, packages/select/index.js, pages/includes/scripts.js, vite.config.js
This was supposed to be done together with corresponding changes from https://github.com/warp-ds/vue/pull/18 so before we announce a stable FINN prod version of this package, this had to be fixed, too.
Before:
After:
Also:
- apply unocss to the internal docs document for easier testing
- fix a bug where w-card's hidden button was visible
=> fix(select): add component classes to select

package.json, pnpm-lock.yaml
With this setup @warp-ds/elements will be compatible with [tokens](https://assets.finn.no/pkg/@warp-ds/tokens/v1/finn-no.css) currently available in FINN production. After merging this PR and so releasing a new alpha version, we will update [Warp Tech Docs](https://warp-ds.github.io/tech-docs/getting-started/developers/) and suggest the use of this particular version when relying on the above mentioned tokens.
- bump `@warp-ds/uno` to `1.0.0.-alpha.49`
- bump `@warp-ds/component-classes` to `1.0.0.-alpha.116`
Also:
- Fix missing transparent background on buttons in Button of type "link" and suffix for Textfield
Before|After
---|---
=> fix: stable FINN prod alpha-release

elements.css, package.json, packages/affix/index.js, packages/alert/index.js, packages/attention/index.js, packages/box/index.js, packages/breadcrumbs/index.js, packages/button/index.js, packages/card/index.js, packages/expandable/index.js, packages/select/index.js, packages/textfield/index.js, packages/toast/toast-container.js, packages/toast/toast.js, pages/includes/head.html, pnpm-lock.yaml, tests/utils/index.js, vite.config.js
Fixes [Warp-185](https://nmp-jira.atlassian.net/browse/WARP-185?atlOrigin=eyJpIjoiNTI4YmYyMzExYzJmNGQ0ZDkyYzg0YmVlODUzYTMzZWMiLCJwIjoiaiJ9)
In this PR we are supporting the new semantic classes that was a breaking change in the @warp-ds/css@1.0.0-alpha.33.
Changes include:
- bump @warp-ds/uno to -alpha.60 & @warp-ds/css to -alpha.33
- import component classes from @warp-ds/css/component-classes
- use new semantic color tokens from @warp-ds/css/1.0.0-alpha.33
- use new resets in uno config
Now that we have own new css repo which contains component-classes we need to update dependencies and imports
All components in this repo are getting shipped together with all css needed. We are safelisting the component classes here. I wonder if we want to import the components.css here instead? 🤔 To …
=> fix: use css packages instead of component-classes

CHANGELOG.md, package.json
The release job failed in https://github.com/warp-ds/elements/actions/runs/5551876426/jobs/10138511203 so we need to trigger it again by:
a) removing the 1.0.0-alpha.28 tag from https://github.com/warp-ds/elements/tags
b) reverting the last semantic-release-bot commit: 81ca835160352825353caaf3c0664cc93fb7a15a.
c) setting `fix:` prefix on the PR title to tell semantic-release we want our changes released.
=> fix: trigger release of 1.0.0-alpha.28

elements.css, package.json, pages/includes/head.html, pnpm-lock.yaml, tests/utils/index.js, vite.config.js
Bumping @warp-ds/css package includes a fix for the select chevron in component classes
=> chore: bump @warp-ds/css package and update eik urls

packages/broadcast/component.js, packages/toast/api.js, packages/utils/index.js, packages/utils/window-exists.js
The toast API relies on a utility function to prevent browser APIs from being called in a non-browser environment (eg. Node). The utility function identifies non-browser environments by checking  if the window object is defined. The function was imported from a package that also imported the classmap function from lit-html, which in itself contains a reference to the window object on top-level of the module. This causes server-side rendering to fail as soon as the imported modules are parsed and evaluated.
To fix this issue, the utility function in question is moved to a separate module that does not contain transitive references to the window object, and it can now safely be used for server-side rendering.
=> fix(@warp-ds/toast): remove window reference from toast api bundle, fixing server-side rendering

package.json
Make toast api available in the npm package.
=> fix(package.json): build toast api to publish missing scripts

pages/includes/scripts.js
=> fix: provide correct import of windowExists after refactoring

.github/workflows/release.yml, .github/workflows/update-next.yml, .releaserc.json, CONTRIBUTING.md, README.md
* docs(contributing.md): update default/prerelease branches from alpha to next
* docs(readme.md): remove -S flag from 'npm install' command -S (--save) flag is redundant as of npm v.5.0.0
* docs(readme.md): rephrase the part about next vs. stable release
* ci(release.yml): remove alpha from matched branches
* ci(release.yml): don't auto-update aliased versions on push We want to handle aliasing manually in order to give teams time to test the newest changes
* ci(.releaserc.json): remove alpha from prerelease branches list
* ci(update-next.yml): rename alpha to next branch
=> chore: set next as prerelease branch (#40)

packages/button/index.js
Remove check for a button type as variant will be set to secondary anyway. And the check is also not making any sense. So let's clean up
=> fix: no need for type check as secondary button is default

build-elements.js, packages/expandable/index.js, pages/includes/scripts.js, vite.config.js
Reverts warp-ds/elements#53
We need to import @warp-ds/icons before the merge
=> revert: add lit to rollup options to be able to build icons

pages/components/alert.html, pages/includes/alertControllersScripts.html
Now when clicking controller buttons the Alert closes and opens + its variant and text updates correctly:
=> fix: alert examples

packages/attention/index.js, pages/components/attention.html
Attention's 'popover' property interferes with the new [Popover API](https://developer.chrome.com/docs/web-platform/popover-api/popover-property/) in Google Chrome and causes the popover to not appear.
It was apparent when inspecting style of the `<w-attention>` custom element with `popover` attribute.
```
[popover]:not(:popover-open):not(dialog[open]) {
display: none;
}
```
This PR introduces a quick fix for that, as well as some small style fixes.
=> fix(attention): popover target is visible on Chrome 109

build-elements.js, package.json, packages/expandable/index.js, pages/includes/scripts.js, pnpm-lock.yaml, vite.config.js
Reverts warp-ds/elements#57
I have reverted the PR before as it was too early before we've published the icons. Now it will be possible I think
=> fix: add lit to rollup options to be able to build icons

package.json, pages/components/button.html, pnpm-lock.yaml
- update @warp-ds/css to 1.1.2 to make full-width link (anchor) styled as Button have centered text (Fixes [WARP-347](https://nmp-jira.atlassian.net/browse/WARP-347))
- update @warp-ds/icons to 1.1.0 to fix translations in svg titles
=> fix: anchor text alignment & icon translations

packages/breadcrumbs/index.js
- Fixed the double Aria label
- Removed the aria-hidden from seperators
This component assumes there is only one Breadcrumb on any single page. We should prob. not make assumptions like this anymore in any of or components and perhaps look into as separate tasks: 
- Random key gen all(?) ID's  (as in moving/modernizing this <code>@warp-ds/elements/packages/utils/index.js</code> <code>generateRandomId()</code> to a broader warp toolbox )
- Accept a root heading level if supplied to the component (we prob need to modernize the <code>unstyled-heading.js</code> script for this)
=> fix(breadcrumbs): Accessability fix

pages/components/alert.html, pages/includes/alertControllersScripts.html
Fixes [WARP-319](https://nmp-jira.atlassian.net/browse/WARP-319)
- add `aria-controls` and `aria-expanded` to buttons controlling visibility of Alert
- replace `p`-elements with `h3` to represent titles
- set `role='status'` for alerts of 'info' or 'positive' variant
Upon merge to `next` Alert page will be updated in https://warp-ds.github.io/elements/alert.html.
=> docs(alert): fix accessibility issues in Alert docs

package.json, pages/includes/scripts.js, pnpm-lock.yaml, vite.config.js
Got too greedy to remove unocss from elements project. But apparently there are some classes that we still need to generate via uno. Hence this PR
=> fix: bring back unocss for our own docs

.github/workflows/crowdin-sync.yml
Trigger crowdin-sync job only on push to next branch and if crowdin.yml or .po files change.
=> chore(crowdin-sync): trigger only on push to next & specify files to track

packages/textfield/test.js, pages/components/textfield.html
Fixes [WARP-337](https://nmp-jira.atlassian.net/browse/WARP-337)
Previously the clear and search Affix button would be announced using its icon's title, which describes the appearance of the icon. However, to satisfy the regulations, the Affix button’s aria-label should describe the purpose of the button, i.e. "Clear text", "Search". A11y team doesn't agree with this and says that we should rather describe its appearance, but Uu-tilsynet’s regulations trump those personal views.
In this PR we pass respective aria-labels to Affix components that render as buttons with icons. This means icons title will not be announced, but just the provided aria-label.
=> docs(textfield): add aria-labels to affix buttons with icons

packages/textfield/index.js, pages/components/textfield.html
Fixes [WARP-374](https://nmp-jira.atlassian.net/browse/WARP-374)
Prefix is an absolutely positioned component and the gap between that component and the `input`'s content is handled using a left padding on the `input`. It’s currently hard-coded to 40px, but with this quick fix we can let users change it by setting a CSS variable in `TextField`’s class (`<TextField class=”[--w-prefix-wdith: 100px]”>`). It’s not dynamic and users will need to calculate how much padding their input needs, but it’s the only non-breaking quick fix we managed to come up with. We should really consider rewriting these form components completely to properly approach styling of different text fields, affixes etc.
=> fix(textfield): allow styling input's left padding when prefix is wider than 40px

package.json, packages/card/index.js, pnpm-lock.yaml
Fixes [WARP-430](https://nmp-jira.atlassian.net/browse/WARP-430)
Background color of a on-flat Card will no longer be inherited from the parent container.
Before:
After:
=> fix(card): set default background on unselected non-flat card

package.json, packages/alert/index.js, packages/toast/toast.js, pages/includes/scripts.js, pnpm-lock.yaml
Fixes [WARP-498](https://nmp-jira.atlassian.net/browse/WARP-498)
This PR updates @warp-ds/icons dependency to 2.0.0 and replaces deprecated icons with the [suggested equivalents](https://warp-ds.github.io/tech-docs/components/icons/#deprecated-icons):
=> fix: rename deleted icons after @warp-ds/icons update to 2.0.0

package.json, packages/select/index.js, packages/textfield/index.js, pnpm-lock.yaml
Depends on https://github.com/warp-ds/css/pull/180
Fixes [WARP-515](https://nmp-jira.atlassian.net/browse/WARP-515)
Changes based on the [Figma component library](https://www.figma.com/file/oHBCzDdJxHQ6fmFLYWUltf/Warp---Components-2.0?type=design&node-id=954-37013&mode=design&t=NPcTtpnw8dXLMG36-0):
- label color doesn't change when input is invalid
- label optional should have subtle text color (the other changes to label optional should be handled in a separate task)
- helpText color should be negative when input is invalid
=> fix: use correct colors in label and error text

package.json, packages/attention/index.js, pages/components/attention.html, pnpm-lock.yaml
**Part of fixes for Jira-tickets:** [WARP-432](https://nmp-jira.atlassian.net/browse/WARP-432), [WARP-341](https://nmp-jira.atlassian.net/browse/WARP-341) & [WARP-373](https://nmp-jira.atlassian.net/browse/WARP-373)
- Add `cross-axis` prop
- Only render attention component when `targetEl` is not undefined or when it is a `callout`
- Bump to latest version of `@warp-ds/core` dependency
=> feat: add more functionality to attention component

.github/workflows/deploy-docs.yml, .github/workflows/i18n.yml, .github/workflows/lint.pr.yaml, .github/workflows/preview.yml, .github/workflows/release.yml, package.json, packages/textfield/index.js, pnpm-lock.yaml
Use cleaned up input component classes to avoid buggy style overriding when utility classes styling the same CSS properties were applied to the same element
- Update @warp-ds/uno to 1.12.0 in order to handle padding classes with arbitrary values that contain CSS variables (e.g. `pl-[var(--w-prefix-width,_40px)]`
- Use the cleaned up input component classes to avoid style overriding
- replaced fclasses() with classes() call to avoid `undefined` classes overriding the defined ones
- Set the pnpm version to v9 in github workflows to avoid lockfile issues after updating pnpm locally
Tested with TextField and Textarea.
=> fix(textfield): clean up classes

package.json, pnpm-lock.yaml
This PR updates the @warp-ds/elements-core package to ensure `WarpElement` extended by our web components is based on the same version locally and on Eik/NPM.
Additionally, @warp-ds/icons and @warp-ds/css were also updated, although those updates don't introduce any changes relevant to this package.
=> chore(deps): update warp depenendencies

package.json, pages/components/attention.html, pnpm-lock.yaml
Fixes Jira [WARP-527](https://nmp-jira.atlassian.net/browse/WARP-527)
- Update to latest version of @warp-ds/core dependency
- Add class `mr-8` to the callout example in `attention.html`.
**Note:**
- Unlike in [@warp-ds/react](https://github.com/warp-ds/react/pull/248) and [@warp-ds/vue](https://github.com/warp-ds/vue/pull/170), we do not need to create a default div for `targetEl`, since you always have to have  `slot="target"` defined for the attention-component in @warp-ds/elements, regardless of whether callout is `true` or `false`.
**Tested:**
- Tested in Chrome, Firefox and Safari
- Also tested in Server-side rendered app
=> fix: add a mr-8 to calloutTarget div

.github/workflows/release.yml
Sometimes we get this error when trying to make a semantic release after having merged a PR: 
`"An error occurred while running semantic-release: RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again."`
This PR updates the `release.yml` file so that it will try 3 times to make a semantic release, and only if it has successfully made a semantic-release will it publish to EIK.
=> fix: update release.yml to include retry for semantic-release and only if succesful will it publish to eik

package.json, packages/select/index.js, pages/components/select.html, pnpm-lock.yaml
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the Select component.
Additionally this PR has:
-  Added missing props `disabled` and `readOnly` to Select component
- Added missing Select examples for `disabled` and `readOnly`.
- Added a `handleKeyDown()` function to disable `space`, `arrowUp` and `arrowDown` for when `readOnly` prop is set to `true`
- Added a more interactive invalid example (where the invalid state will be removed if the user chooses the right choice). 
Either link this branch with @warp-ds/css (`fix/clean-up-select-classes` branch) or replace this for @warp-ds/css dependency in package.json: `github:warp-ds/css#component-classes-cleanup` with this  `github:warp-ds/css#fix/clean-up-select-classes`
=> fix(select): clean up classes

package.json, packages/toast/toast.js, pnpm-lock.yaml
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `Toast` component.
**Changes:**
- Renamed `toast` classes in `toast.js`
- Replaced `classes` function with `classNames` from `'@chbphone55/classnames'`
- Use `kebabCaseAttributes` in `toast.js`
Either link this branch with @warp-ds/css (`fix/cleanup-toast-classes` branch) or replace this for @warp-ds/css dependency in package.json: `github:warp-ds/css#component-classes-cleanup` with this  `github:warp-ds/css#fix/cleanup-toast-classes`
=> fix(toast): clean up classes

packages/expandable/index.js, packages/expandable/test.js, pages/components/expandable.html, pages/includes/expandableControllers.html, pnpm-lock.yaml
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `Expandable` component.
**Changes:**
- Renamed classNames in `Expandable` component.
- Refactored `Expandable` component
- Remove deprecated `info` prop
- Replace `paddingTop` with `contentWithTitle`
Either link this branch with @warp-ds/css (`fix/cleanup-expandable-component` branch) or replace this for @warp-ds/css dependency in package.json: `github:warp-ds/css#component-classes-cleanup` with this  `github:warp-ds/css#fix/cleanup-expandable-component`
=> fix(expandable): clean up classes

crowdin.yml, lingui.config.ts, packages/modal/locales/da/messages.mjs, packages/modal/locales/da/messages.po, packages/modal/locales/en/messages.mjs, packages/modal/locales/en/messages.po, packages/modal/locales/fi/messages.mjs, packages/modal/locales/fi/messages.po, packages/modal/locales/nb/messages.mjs, packages/modal/locales/nb/messages.po, packages/modal/modal-header.js
This change aligns Modal Element with React/Vue Modal implementations, but above all helps screen reader users understand what's the purpose of the modal header navigation buttons. The translations for Danish, Finnish and Norwegian were copied over from [React Modal locales](https://github.com/warp-ds/react/tree/next/packages/modal/src/locales).
- works with VoiceOver on Chrome/Safari/Firefox
- the translations are applied correctly in all language versions of a running test app
=> fix(modal): add aria labels to back and close buttons

packages/badge/index.js, pages/components/badge.html
The notification variant of Badge is no longer supported in Warp and a corresponding token was removed from @warp-ds/css v2.0.0. This PR removes "notification" variant from Badge properties and cleans up the docs examples.
=> fix(badge): remove deprecated 'notification' example

package.json, pnpm-lock.yaml
Part of fixing JIRA issue: [WARP-607](https://nmp-jira.atlassian.net/browse/WARP-607)
**Changes:**
- Bump to latest version of `@warp-ds/core` to get the recent changes (where padding has been added to the attention-element)
=> fix(attention): bump to latest version of @warp-ds/core dependency

packages/attention/index.js
Fixes Jira issue: [WARP-651](https://nmp-jira.atlassian.net/browse/WARP-651)
**Changes include:**
- Move `role` and `aria-label` from the `div` wrapping the speech bubble to a `div` that is wrapping the attention `this._arrowHtml` component
=> fix(attention): move role and aria-label to attention-arrow wrapper

packages/select/index.js
https://nmp-jira.atlassian.net/browse/WARP-647.
Adds a custom change event to the select component, which fires on dropdown change.
The dropdown value is available on the `detail` field.
To use in Svelte and other libraries (without a wrapper), add event listeners manually (using addEventListener).
=> fix: Add select element change event

packages/attention/index.js
Improve attention component by running the recompute function on render.
Ensures that arrow/highlight position is computed correctly on first render, giving correct styling if the highlight is shown by default.
=> fix: Improve attention component styling

package.json
Allow any 2.x
Fixes a peer dependency warning when I have `2.0.1`
```
 WARN  Issues with peer dependencies found
.
└─┬ @warp-ds/elements 2.0.1
└── ✕ unmet peer @warp-ds/css@2.0.0: found 2.0.1
```
=> fix: ease strictness of warp-ds/css peer dependency

.gitignore, package.json, packages/alert/alert.test.ts, packages/alert/index.ts, pnpm-lock.yaml, setup-tests.ts, vitest.config.ts
in order to look inside the shadowDom we need to make additions to the vitest setup.
`setup-tests.ts` contains what is needed for tests similar to those in `alert.test.js`
=> fix: adding setup test script for tests

packages/button/button.test.ts, packages/datepicker/DatePicker.test.tsx, packages/datepicker/datepicker.test.ts, packages/datepicker/datepicker.ts
The calendar is rewritten as a focus-trapped modal to have it announced (in my opinion) in a better way for screen readers. This is in line with the example from the ARIA Author Practices Guide
https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/
For the announcement to work correctly we can't conditionally render the calendar, it must be present in the document. We toggle its presence both visual and in the accessibility tree with display: none;
=> chore: accessibility refactor for screen readers

packages/expandable/index.ts
In storybook, utils gets added separately but in the bundle they weren't getting included.
=> fix: add missing utility dependencies
