package.json
packages/textfield/index.js
pnpm-lock.yaml

Can be tested on http://localhost:xxxx/pages/components/textfield.html

fix: add styles to textfield

---

.github/workflows/release.yml
pnpm-lock.yaml

Hopefully fixes this error: https://github.com/warp-ds/elements/actions/runs/4795223687/jobs/8529517491

fix(release.yml): set pnpm version to 8 to fix recursive install errors

---

package.json
pnpm-lock.yaml

Hopefully fixes this error: https://github.com/warp-ds/elements/actions/runs/4795223687/jobs/8529517491

fix: remove unused @finn-no/browserslist-config dep

---

package.json
packages/alert/index.js
pnpm-lock.yaml

feat(alert): warpify alert component

---

package.json
packages/expandable/index.js
pnpm-lock.yaml

Fix issue with wrong alignment of the chevron
https://trello.com/c/WrlChPyH/273-expandable-fix-chevron-line-height-issue

fix(expandable): fix chevron issue

---

CONTRIBUTING.md
README.md

Update readme and contriubutin:
* Need to run `pnpm build` before `pnpm dev`
* Change from Vue3 to Web Components 😅

docs: update README and CONTRIBUTING

---

package.json
packages/button/index.js
pnpm-lock.yaml

Can be tested here: http://localhost:5178/pages/components/button.html
Before|After
---|---

fix: use new button classes and improve conditions

---

build-elements.js
packages/expandable/index.js
pages/includes/scripts.js
vite.config.js

Fixes 👇 and adds some needed renaming
Draft as we haven't published icons yet

fix: add lit to rollup options to be able to build icons

---

package.json
packages/button/index.js
pages/components/button.html
pnpm-lock.yaml

This ticket adds a fullwidth prop to the button component.
To test: Link with this PR in the css-repo: https://github.com/warp-ds/css/pull/51

fix: Add fullwidth button prop

---

vite.config.js

While testing the Elements docs I thought it's time for a quick cleanup in this file to make it easier to browse through :)

chore(vite.config.js): remove redundant and unused code

---

.github/workflows/deploy-pages.yml
.gitignore
package.json
vite.config.js

1. pointed the gh-pages branch(that I created) in the GH settings
2. this PR will add a workflow for building the gh pages.
So hopefully we merge this workflow will kick in the build and our docs pages will be published 🤞

chore: publish elements docs

---

.github/workflows/crowdin-sync.yml
crowdin.yml

Implemented the same way as it was done in Vue: https://github.com/warp-ds/vue/pull/65/files

chore(workflows): set up synchronization with crowdin

---

pages/components/badge.html

...and fixed texts for positioned badges

docs: Change to use an unordered list for listing badge variants for a11y reasons

---

package.json
packages/expandable/index.js
pnpm-lock.yaml

Update the css-variables for chevron for the expandable-component

fix: changed css for expandable

---

.gitignore
README.md
build-elements-eik.js
package.json
pnpm-lock.yaml

Solves this JIRA-ticket: [WARP-381](https://nmp-jira.atlassian.net/browse/WARP-381)

fix: eik publishing for elements

---

crowdin.yml
lingui.config.ts
packages/toast/locales/en/messages.mjs
packages/toast/locales/en/messages.po
packages/toast/locales/fi/messages.mjs
packages/toast/locales/fi/messages.po
packages/toast/locales/nb/messages.mjs
packages/toast/locales/nb/messages.po
packages/toast/toast.js

Fixes JIRA ticket: [WARP-348](https://nmp-jira.atlassian.net/browse/WARP-348)
- Add translation to aria-label in toast component.

fix: add translation for toast aria-label

---

.github/workflows/release.yml
CONTRIBUTING.md
build.js
index.html
package.json
pnpm-lock.yaml

This reverts commit 9253ed081d1fbe967db5830dc45b6d0df38f737f.

revert: "Remove eik from Elements (#124)"

---

package.json
packages/card/index.js
pnpm-lock.yaml

Utilise styling fixes from component classes in the Card component.
https://github.com/warp-ds/elements/assets/7531505/3c7e230e-453c-41b3-92ae-d3e5d67f9170

fix: Styling fixes for Card component

---

packages/toast/api.js
packages/toast/test.js

Reported here: https://sch-chat.slack.com/archives/C04P0GYTHPV/p1713216068414779

chore: Remove info type leftovers from Toast

---

.github/workflows/deploy-docs.yml
.github/workflows/i18n.yml
.github/workflows/lint.pr.yaml
.github/workflows/preview.yml
.github/workflows/release.yml
CHANGELOG.md
package.json
packages/attention/index.js
packages/card/index.js
packages/textfield/index.js
packages/toast/api.js
packages/toast/test.js
pages/components/attention.html
pnpm-lock.yaml

Note: Eik v1 alias for @warp-ds/css needs to be update to 1.9.6 before this release PR can be merged.

Release 1.4.0

---

.github/workflows/deploy-docs.yml
.github/workflows/i18n.yml
.github/workflows/lint.pr.yaml
.github/workflows/preview.yml
.github/workflows/release.yml
package.json
pages/includes/head.html
pnpm-lock.yaml
tests/utils/index.js

BREAKING CHANGE: This removes depreacted stuff

feat: release for DBA

---

packages/toast/toast-container.js
pnpm-lock.yaml

Depends on https://github.com/warp-ds/css/pull/235

refactor(toast-container): rename component classes key

---

package.json
pnpm-lock.yaml

Fixes JIRA issue: [WARP-657](https://nmp-jira.atlassian.net/browse/WARP-657)
- Bump to latest version of @warp-ds/core dependency

fix(attention): update to latest version of @warp-ds/core dependency

---

.github/workflows/lint.pr.yaml
.github/workflows/release.yml
package.json
packages/button/button.test.ts
packages/button/index.ts
packages/modal/modal-header.ts
packages/modal/modal-main.ts
pnpm-lock.yaml
vitest.config.ts

test: add vitest, playwright, example test

---

packages/card/index.ts

refactor: migrate card to TS

---

index.js
packages/dead-toggle/index.ts
packages/modal/modal-footer.ts
packages/modal/modal-header.ts
packages/modal/modal-main.ts
pages/components/deadtoggle.html
pages/navigation-data.js
vite.config.js

chore(dead-toggle): Implement dead-toggle

---

pages/components/alert.html
pages/components/attention.html
pages/components/badge.html
pages/components/box.html
pages/components/breadcrumbs.html
pages/components/button.html
pages/components/card.html
pages/components/expandable.html
pages/components/modal.html
pages/components/pill.html
pages/components/select.html
pages/components/textfield.html
pages/components/toast.html
pages/includes/head.html

Just annoyed me that the pages flashed so badly

chore: prevent fouce on docs pages

---

.cem/custom-element-manifest.config.js
.vscode/settings.json
README.md
build.js
docs/@warp-ds/Elements.mdx
index.html
package.json
packages/expandable/index.ts
packages/modal/modal-header.ts
packages/modal/modal-main.ts
packages/rip-and-tear-radio/radio-group.ts
patches/custom-element-vs-code-integration.patch
pnpm-lock.yaml

If you use VS Code I set up the configuration here in the workspace. Try it out in any HTML file!

docs: generate editor helpers, add instructions for use
